NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('news/', include('news.urls')),

]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostSearch, PostCreate, PostUpdate, PostDelete, delete_comment, \
    CategoryListView, subscribe_unsubscribe
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('', PostList.as_view(), name='news_list'),
    path('<int:pk>', PostDetail.as_view(), name='news_detail'),
    path('search/', PostSearch.as_view(), name='news_search'),
    path('create/', PostCreate.as_view(), name='news_create'),
    path('<int:pk>/update/', PostUpdate.as_view(), name='news_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='news_delete'),
    path('<int:pk>/del/', delete_comment, name='delete_comment'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe_unsubscribe, name='subscribe_unsubscribe'),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse
from django.core.cache import cache
from django.db.models import Sum


class Author(models.Model):
    rating = models.IntegerField(default=0)
    users = models.OneToOneField(User,
                                 on_delete=models.CASCADE)

    def update_rating(self):
        postRait = sum(Post.objects.filter(postAuthor=self).values_list('rating', flat=True))
        if postRait is None:
            postRait = 0

        commentRait = sum(Comment.objects.filter(userComment__username=self).values_list('rating', flat=True))
        if commentRait is None:
            commentRait = 0

        commentPostRait = sum(Comment.objects.filter(postComment__postAuthor=self).values_list('rating', flat=True))
        if commentPostRait is None:
            commentPostRait = 0

        self.rating = postRait * 3 + commentRait + commentPostRait
        self.save()

    def __str__(self):
        return f'{self.users}'


class Category(models.Model):
    categories = models.CharField(max_length=255,
                                  unique=True)
    subscribers = models.ManyToManyField(User,
                                         related_name='sub_categories',
                                         through='SubscribeCategories')

    def __str__(self):
        return f'{self.categories}'

    def get_subscribers(self):
        return ",\n".join([str(p) for p in self.subscribers.all()])


class Post(models.Model):
    posts = 'PT'
    news = 'NS'

    TYPES = [
        (posts, 'Статья'),
        (news, 'Новость')
    ]

    postsOrNews = models.CharField(max_length=2,
                                   choices=TYPES,
                                   default=posts)
    timeIn = models.DateTimeField(auto_now_add=True)
    header = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    postAuthor = models.ForeignKey(Author,
                                   on_delete=models.CASCADE)
    postCategories = models.ManyToManyField(Category,
                                            through='PostCategory')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:128] + '...'

    def __str__(self):
        return f'{self.text}'

    def get_absolute_url(self):
        return reverse('news_list')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)


class SubscribeCategories(models.Model):
    subscriber = models.ForeignKey(User,
                                   on_delete=models.CASCADE)
    subCategory = models.ForeignKey(Category,
                                    on_delete=models.CASCADE)


class Comment(models.Model):
    comments = models.CharField(max_length=255)
    timeIn = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    postComment = models.ForeignKey(Post,
                                    on_delete=models.CASCADE)
    userComment = models.ForeignKey(User,
                                    on_delete=models.CASCADE)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import redirect

from .models import Post, Category, Comment


class PostForm(forms.ModelForm):
    header = forms.CharField(min_length=20,
                             label='Заголовок публикации')
    text = forms.CharField(label='Текст публикации',
                           widget=forms.Textarea)
    postCategories = forms.ModelMultipleChoiceField(label='Категория публикации',
                                                    queryset=Category.objects.all(),
                                                    widget=forms.SelectMultiple)
    postsOrNews = forms.ChoiceField(label='Тип публикации',
                                    choices=Post.TYPES)

    class Meta:
        model = Post
        fields = [
            'header',
            'text',
            'postCategories',
            'postsOrNews',

        ]

    def clean(self):
        cleaned_data = super(PostForm, self).clean()

        header = cleaned_data.get('header')
        if header[0].islower():
            raise ValidationError(
                'Заголовок должен начинаться с заглавной буквы.'
            )

        text = cleaned_data.get('text')
        if text is None:
            raise ValidationError(
                'Поле не может быть пустым.'
            )
        if text[0].islower():
            raise ValidationError(
                'Текст публикации должен начинаться с заглавной буквы.'
            )
        if text is not None and text == header:
            raise ValidationError(
                'Текст публикации не должен быть идентичен заголовку публикации.'
            )

        return cleaned_data


class CommentForm(forms.ModelForm):
    comments = forms.CharField(max_length=80,
                               label='Ваш комментарий',
                               )

    class Meta:
        model = Comment
        fields = [
            'comments',
        ]

    def clean(self):
        cleaned_data = super(CommentForm, self).clean()

        comments = cleaned_data.get('comments')
        if comments is None:
            raise ValidationError(
                'Поле не может быть пустым.'
            )
        if comments[0].islower():
            raise ValidationError(
                'Текст публикации должен начинаться с заглавной буквы.'
            )

        return cleaned_data

news/views.py
from datetime import datetime, timedelta

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from django.core.cache import cache

from news.custom_mixins import OwnerPermissionRequiredMixin

from NewsPortal import settings
from .models import Post, Comment, Author, Category, SubscribeCategories
from .filters import PostFilter
from .forms import PostForm, CommentForm
from datetime import datetime, timedelta


class PostList(ListView):
    model = Post
    ordering = '-timeIn'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_author'] = self.request.user.groups.filter(name='authors').exists()
        return context


class PostSearch(ListView):
    model = Post
    ordering = '-timeIn'
    template_name = 'newsSearch.html'
    context_object_name = 'news'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView, FormMixin):
    model = Post
    form_class = CommentForm
    template_name = 'oneNews.html'
    context_object_name = 'oneNews'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_now'] = self.request.user
        context['commnts'] = Comment.objects.filter(postComment=self.kwargs.get("pk"))
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.form = form.save(commit=False)
        self.form.postComment = Post.objects.get(pk=self.kwargs.get("pk"))
        self.form.userComment = self.request.user
        form.save()
        return super(PostDetail, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('news_detail', kwargs={'pk': self.kwargs.get('pk')})

    def get_object(self, *args, **kwargs):
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        # кэш очень похож на словарь, и метод get действует так же.
        # Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)

        return obj


def delete_comment(request, **kwargs):
    selected_comments = Comment.objects.get(pk=int(kwargs['pk']))
    selected_comments.delete()
    return redirect(request.META.get('HTTP_REFERER'))


class PostCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'newsCreate.html'

    def form_valid(self, form):
        form.instance.postAuthor = self.request.user.author
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        limits: int = settings.DAILY_POST_LIMIT
        prev_day = datetime.now() - timedelta(days=1)
        posts_day_count: list = Post.objects.filter(postAuthor__users=self.request.user,
                                                    timeIn__gte=prev_day)
        context['post_limits'] = limits > len(posts_day_count)
        return context


class PostUpdate(OwnerPermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'newsUpdate.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.postAuthor = Author.objects.get(users=self.request.user)
        return super().form_valid(form)


class PostDelete(OwnerPermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'newsDelete.html'
    success_url = reverse_lazy('news_list')


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.postCategories = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(postCategories=self.postCategories).order_by('-timeIn')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.postCategories.subscribers.all()
        context['category'] = self.postCategories
        return context


def subscribe_unsubscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    sample_html = ''
    if user not in category.subscribers.all():
        category.subscribers.add(user)
        sample_html = 'account/email/email_subscribe_information.html'
    elif user in category.subscribers.all():
        category.subscribers.remove(user)
        sample_html = 'account/email/email_unsubscribe_information.html'

    html_content = render_to_string(
        sample_html,
        {
            'new_user': user.username,
            'link': f'{settings.SITE_URL}/news/',
            'categories': category,
            'category_link': f'{settings.SITE_URL}/news/categories/{pk}'
        }
    )

    msg = EmailMultiAlternatives(
        subject='Информация о подписке',
        body='',
        from_email='yuran4ek37@yandex.ru',
        to=[user.email],
    )
    msg.attach_alternative(html_content, 'text/html')
    msg.send()

    return redirect(request.META.get('HTTP_REFERER'))
    # return render(request, s_html, {'category': category})

templates/become_author.html
{% extends "flatpages/default.html" %}

{% block content %}

<h1>Поздравляем, Вы стали автором!</h1>
<div class="line"></div>
<h3>Теперь Вы можете:<br>
    <h5>делать публикации на нашем портале,<br>
        редактировать и удалять свои публикации<br>
    </h5>
</h3>
<div class="line"></div>
<h3>
    Выберете дальнейшие действия:<br>
</h3>
    <h5>
        <a href="{% url 'news_list' %}" class="btn btn-outline-dark btn-sm">Вернуться на главную</a><br>
        или<br>
        <a href="{% url 'news_create' %}" class="btn btn-outline-success btn-sm">Создать публикацию</a>
    </h5>
{% endblock content %}

templates/category_list.html
<!-- наследуемся от шаблона default.html, который мы создавали для flatpages
-->
{% extends 'flatpages/default.html' %}

{% load custom_filter %}

{% load custom_tags %}

<!-- Название у нас будет Posts -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    <h1 class="text-center">Категория "{{ category }}"</h1>
    {% if is_not_subscriber %}
        <p class="text-center">
            <a href="{% url 'subscribe_unsubscribe' category.id %}" class="btn btn-outline-success btn-sm">
            Подписаться на категорию</a>
        </p>
    {% else %}
    <div class="line"></div>
        <p class="text-center">
            <h3>Вы подписаны на рассылку о новостях данной категории</h3>
            <a href="{% url 'subscribe_unsubscribe' category.id %}" class="btn btn-outline-danger btn-sm">
                Отписаться от категории</a>
        </p>
    {% endif %}
    <div class="line"></div>
        {% if category_news_list %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Тип публикации</th>
                    <th scope="col">Заголовок публикации</th>
                    <th scope="col">Дата публикации</th>
                    <th scope="col">Превью публикации</th>
                    <th scope="col">Публикация</th>
                    {% if perms.news.change_post %}
                        <th scope="col">Изменить публикацию</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for post in category_news_list %}
                <tr>
                    <td>{{ post.get_postsOrNews_display }}</td>
                    <td>{{ post.header|censor }}</td>
                    <td>{{ post.timeIn|date:'d.m.Y'}}</td>
                    <td>{{ post.text|truncatewords:20|censor }}</td>
                    <td><a href="{% url 'news_detail' post.id %}">Узнать подробнее</a></td>
                        {% if perms.news.change_post %}
                            <td><a href="{% url 'news_update' post.id %}">Изменить</a> </td>
                        {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>Публикации отсутствуют</h2>
    {% endif %}
{% endblock content %}

templates/deleteComment.html
{% extends 'flatpages/default.html' %}

{% load custom_filter %}

{% block content %}
<h1>Комментарий к публикации</h1>

<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <h3>Удалям:</h3>
        <h5>"{{ object.comments|censor }}"?</h5>
    <input type="submit" value="Удалить комментарий" />
</form>

{% endblock content %}

templates/news.html
<!-- наследуемся от шаблона default.html, который мы создавали для flatpages
-->
{% extends 'flatpages/default.html' %}

{% load custom_filter %}

{% load custom_tags %}

<!-- Название у нас будет Posts -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}

    <h3>
        <td>Общее количество публикаций на портале: </td>
        <!-- {{ news | length }} out of --> {{ paginator.count }}
    </h3>
    <div class="line"></div>
    <h5>
        <a href="{% url 'news_search' %}" class="btn btn-outline-primary btn-sm">Поиск публикаций</a>
    </h5>
    {% if perms.news.add_post %}
    <h5>
        <a href="{% url 'news_create' %}" class="btn btn-outline-success btn-sm">Создать публикацию</a>
    </h5>
    {% endif %}

    {% if not is_author %}
    <h5>
        <a href="{% url 'become_author' %}" class="btn btn-outline-info btn-sm">Стать автором</a>
    </h5>
    {% endif %}
    <div class="line"></div>
    {% if news %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Тип публикации</th>
                    <th scope="col">Категории публикации</th>
                    <th scope="col">Заголовок публикации</th>
                    <th scope="col">Дата публикации</th>
                    <th scope="col">Превью публикации</th>
                    <th scope="col">Публикация</th>
                    {% if perms.news.change_post %}
                        <th scope="col">Изменить публикацию</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for post in news %}
                <tr>
                    <td>{{ post.get_postsOrNews_display }}</td>
                    <td>
                        {% for category in post.postCategories.all %}
                            {% if not forloop.last %}
                                <a href="{% url 'category_list' category.id %}">{{ category.categories }},</a>
                            {% else %}
                                <a href="{% url 'category_list' category.id %}">{{ category.categories }}</a>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ post.header|truncatewords:5|censor }}</td>
                    <td>{{ post.timeIn|date:'d.m.Y'}}</td>
                    <td>{{ post.text|truncatewords:10|censor }}</td>
                    <td><a href="{{ post.id }}">Узнать подробнее</a></td>
                    {% if perms.news.change_post %}
                        <td><a href="{% url 'news_update' post.id %}">Изменить</a> </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>Публикации отсутствуют</h2>
    {% endif %}

    <h6>страницы</h6>

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=page_obj.previous_page_number %}">предыдущая</a>
    {% endif %}

    {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">следующая</a>
    {% endif %}

{% endblock content %}

templates/newsCreate.html
{% extends 'flatpages/default.html' %}

{% block content %}
{% if post_limits %}
    <h1>Новая публикация</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success btn-sm" value="Опубликовать" />
    </form>
{% else %}
<h1>
    Уважаемый автор!
</h1>
    <h3>
        Вы можете создавать не более 3 постов в день. <br>
        Ждём вас завтра!
    </h3>
{% endif %}


{% endblock content %}

templates/newsDelete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление публикации</h1>

<hr>
<form action="" method="post">
    {% csrf_token %}
    <h3>Удаляем:</h3>
        <h5>"{{ object.get_postsOrNews_display }}"</h5>
        <h5>"{{ object.header }}"?</h5>
    <input type="submit" class="btn btn-outline-danger btn-sm" value="Удалить публикацию" />
</form>
{% endblock content %}

templates/newsSearch.html
<!-- наследуемся от шаблона default.html, который мы создавали для flatpages
-->
{% extends 'flatpages/default.html' %}

{% load custom_filter %}

{% load custom_tags %}

<!-- Название у нас будет Posts -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    <h3>
        <td>Количество найденных публикаций: </td>
        {{ news | length }}
    </h3>

    {% if perms.news.add_post %}
    <div class="line"></div>
    <h5>
        <a href="{% url 'news_create' %}" class="btn btn-outline-success btn-sm">Создать публикацию</a>
    </h5>
    {% endif %}

    <hr>
        <form action="" method="get">
            <h5>{{ filterset.form.as_p }}</h5>
            <!--<input type="datetime-local" id="timeIn"
            name="timeIn" value="{{ filters.form.timeIn }}"> -->
            <input type="submit" class="btn btn-outline-primary btn-sm" value="Найти" />
        </form>
    <hr>
    {% if news %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Тип публикации</th>
                    <th scope="col">Категории публикации</th>
                    <th scope="col">Заголовок публикации</th>
                    <th scope="col">Дата публикации</th>
                    <th scope="col">Превью публикации</th>
                    <th scope="col">Публикация</th>
                    {% if perms.news.change_post %}
                        <th scope="col">Изменить публикацию</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {% for post in news %}
                <tr>
                    <td>{{ post.get_postsOrNews_display }}</td>
                    <td>
                        {% for category in post.postCategories.all %}
                            {% if not forloop.last %}
                                <a href="{% url 'category_list' category.id %}">{{ category.categories }},</a>
                            {% else %}
                                <a href="{% url 'category_list' category.id %}">{{ category.categories }}</a>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ post.header|truncatewords:5|censor }}</td>
                    <td>{{ post.timeIn|date:'d.m.Y'}}</td>
                    <td>{{ post.text|truncatewords:10|censor }}</td>
                    <td><a href="{% url 'news_detail' post.id %}">Узнать подробнее</a></td>
                        {% if perms.news.change_post %}
                            <td><a href="{% url 'news_update' post.id %}">Изменить</a> </td>
                        {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>Публикации не найдены</h2>
    {% endif %}

    <h6>страницы</h6>

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=page_obj.previous_page_number %}">предыдущая</a>
    {% endif %}

    {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">следующая</a>
    {% endif %}

{% endblock content %}

templates/newsUpdate.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Обновить публикацию</h1>

<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-outline-success btn-sm" value="Обновить" />
</form>
    <div class="line"></div>
    <h5>
        <a href="{% url 'news_delete' post.id %}" class="btn btn-outline-danger btn-sm">Удалить публикацию</a>
    </h5>

{% endblock content %}

templates/oneNews.html
<!-- наследуемся от шаблона default.html, который мы создавали для
flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filter %}

<!-- Название у нас будет Post -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим саму новость, идентификатор
которого был передан в url -->
{% block content %}

    <h4><b>Заголовок публикации</b></h4>
        <h5>{{ oneNews.header|censor }}</h5>
    <div class="line"></div>
    <h4><b>Дата публикации</b></h4>
        <h5>{{ oneNews.timeIn|date:'d.m.Y' }}</h5>
    <div class="line"></div>
    <h4><b>Категории публикации</b></h4>
        <h5>
            {% for category in oneNews.postCategories.all %}
                {% if not forloop.last %}
                    <a href="{% url 'category_list' category.id %}">{{ category.categories }}, </a>
                {% else %}
                    <a href="{% url 'category_list' category.id %}">{{ category.categories }}</a>
                {% endif %}
            {% endfor %}
        </h5>
        <div class="line"></div>
    <h4><b>Текст публикации</b></h4>
    <div align="left">
        <h5>{{ oneNews.text|censor }}</h5>
    </div>

    {% if perms.news.change_post %}
    <h5>
        <a href="{% url 'news_update' oneNews.id %}" class="btn btn-outline-primary btn-sm">Изменить публикацию</a>
    </h5>
    {% endif %}
    {% if perms.news.delete_post %}
    <h5>
        <a href="{% url 'news_delete' oneNews.id %}" class="btn btn-outline-danger btn-sm">Удалить публикацию</a>
    </h5>
    {% endif %}
    <div class="line"></div>

    <h4><b>Комментарии</b></h4>
    {% for comm in commnts %}
        {% if user_now == comm.userComment %}
            <h5>
                {{ comm.userComment.first_name }} {{ comm.userComment.last_name }}:
                <i>{{ comm.comments|censor }}</i><br>
            </h5>
            <h6>{{ comm.timeIn|date:'d.m.Y H:i' }}</h6>
            <h6>
                <a href="{% url 'delete_comment' comm.id %}" class="btn btn-outline-danger btn-sm">
                    Удалить комментарий</a>
            </h6>
        {% else %}
            <h5>
                {{ comm.userComment.first_name }} {{ comm.userComment.last_name }}:
                <i>{{ comm.comments|censor }}</i><br>
            </h5>
            <h9>{{ comm.timeIn|date:'d.m.Y H:i' }}</h9>
        {% endif %}
    {% endfor %}

    <hr>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
<!--        <button class="btn btn-outline-success btn-sm">Оставить комментарий</button>-->
        <input type="submit" class="btn btn-outline-success btn-sm" value="Оставить комментарий" />
    </form>

{% endblock content %}